/**
 * Search-engine indexability gate.
 *
 * Publishing AI-generated course pages that fail the content QA checks is a sitewide
 * risk, not a per-page one: Google's helpful-content system demotes whole domains over
 * mass-published thin pages. This module makes "may this URL be indexed" a computed
 * property of measured content quality rather than a judgement call.
 *
 * Facts come from a checked-in manifest regenerated by `scripts/seo-index-audit.ts
 * --write`. Thresholds live here, not in the manifest, so moving the bar needs no
 * regeneration. Unknown ids fail closed.
 *
 * Server-only. The manifest is a few hundred KB and must not reach a client bundle.
 */

import manifest from './indexability-manifest.json';

// ─── Manifest shape ────────────────────────────────────────

export interface PageQuality {
  courseId: string;
  sectionIndex: number;
  unitId: string;
  /** Present on lesson records only. */
  lessonId?: string;
  questions: number;
  /** Words the page renders itself: unit/lesson descriptions plus teaching card text. */
  pageWords: number;
  teachingCards: number;
  /** QA violations of severity `error` — structurally broken items. */
  errors: number;
  warnings: number;
}

export interface CourseQuality {
  courseId: string;
  /** Violations the QA checks raise against the course as a whole (CHECK 15). */
  courseWideViolations: number;
}

export interface IndexabilityManifest {
  version: number;
  generatedAt: string;
  /** Fingerprint of the content the manifest was built from; drift means stale. */
  contentHash: string;
  courses: Record<string, CourseQuality>;
  /** Every unit, keyed `${courseId}/${unitId}`. */
  units: Record<string, PageQuality>;
  /**
   * Keyed `${courseId}/${lessonId}`, and holding only lessons that clear the
   * thin-content floors. Absent means not indexable, same as unknown.
   */
  lessons: Record<string, PageQuality>;
}

const MANIFEST: IndexabilityManifest = manifest;

// ─── Thresholds ────────────────────────────────────────────

/** Prose a page must carry on its own. Every lesson in the corpus tops out at 212. */
export const MIN_PAGE_WORDS = 300;

/** Distinct teaching cards a page needs. CHECK 3 caps a lesson at 3, so no lesson qualifies. */
export const MIN_TEACHING_CARDS = 6;

/** Warning-severity violations allowed per question: one slip per twenty items. */
export const MAX_WARNINGS_PER_QUESTION = 0.05;

/** Absolute warning ceiling, so a large unit cannot bank a bigger budget. */
export const MAX_WARNINGS = 3;

/** Indexable units a section hub needs, in count and as a share of its units. */
export const MIN_SECTION_UNITS = 2;
export const MIN_SECTION_SHARE = 0.5;

// ─── Decisions ─────────────────────────────────────────────

export type IndexBlocker =
  | 'unknown-content'
  | 'qa-errors'
  | 'qa-warnings'
  | 'thin-prose'
  | 'too-few-teaching-cards'
  | 'course-wide-violations'
  | 'no-indexable-children';

export interface IndexDecision {
  indexable: boolean;
  blockers: IndexBlocker[];
}

export type IndexTarget =
  | { kind: 'course'; courseId: string }
  | { kind: 'section'; courseId: string; sectionIndex: number }
  | { kind: 'unit'; courseId: string; unitId: string }
  | { kind: 'lesson'; courseId: string; lessonId: string };

const ALLOWED: IndexDecision = { indexable: true, blockers: [] };

function denied(...blockers: IndexBlocker[]): IndexDecision {
  return { indexable: false, blockers };
}

/** Judges one page's own content. Pure — takes facts, not ids. */
export function evaluatePage(quality: PageQuality | undefined): IndexDecision {
  if (!quality) return denied('unknown-content');

  const blockers: IndexBlocker[] = [];
  if (quality.errors > 0) blockers.push('qa-errors');
  if (quality.warnings > MAX_WARNINGS) blockers.push('qa-warnings');
  else if (quality.warnings > quality.questions * MAX_WARNINGS_PER_QUESTION) blockers.push('qa-warnings');
  if (quality.pageWords < MIN_PAGE_WORDS) blockers.push('thin-prose');
  if (quality.teachingCards < MIN_TEACHING_CARDS) blockers.push('too-few-teaching-cards');

  return blockers.length === 0 ? ALLOWED : { indexable: false, blockers };
}

// ─── Manifest lookups ──────────────────────────────────────

let sectionCache: Map<string, PageQuality[]> | null = null;

function unitsBySection(): Map<string, PageQuality[]> {
  if (sectionCache) return sectionCache;
  const grouped = new Map<string, PageQuality[]>();
  for (const unit of Object.values(MANIFEST.units)) {
    const key = `${unit.courseId}/${unit.sectionIndex}`;
    grouped.set(key, [...(grouped.get(key) ?? []), unit]);
  }
  sectionCache = grouped;
  return grouped;
}

function evaluateSection(courseId: string, sectionIndex: number): IndexDecision {
  const units = unitsBySection().get(`${courseId}/${sectionIndex}`);
  if (!units || units.length === 0) return denied('unknown-content');

  const passing = units.filter((u) => evaluatePage(u).indexable).length;
  const enough = passing >= MIN_SECTION_UNITS && passing / units.length >= MIN_SECTION_SHARE;
  return enough ? ALLOWED : denied('no-indexable-children');
}

function evaluateCourse(courseId: string): IndexDecision {
  const course = MANIFEST.courses[courseId];
  if (!course) return denied('unknown-content');
  if (course.courseWideViolations > 0) return denied('course-wide-violations');

  const sections = new Set(
    Object.values(MANIFEST.units).filter((u) => u.courseId === courseId).map((u) => u.sectionIndex),
  );
  const any = [...sections].some((s) => evaluateSection(courseId, s).indexable);
  return any ? ALLOWED : denied('no-indexable-children');
}

// ─── Public API ────────────────────────────────────────────

/** The one question a page route or the sitemap asks. Unrecognised targets are denied. */
export function getIndexDecision(target: IndexTarget): IndexDecision {
  switch (target.kind) {
    case 'course': return evaluateCourse(target.courseId);
    case 'section': return evaluateSection(target.courseId, target.sectionIndex);
    case 'unit': return evaluatePage(MANIFEST.units[`${target.courseId}/${target.unitId}`]);
    case 'lesson': return evaluatePage(MANIFEST.lessons[`${target.courseId}/${target.lessonId}`]);
    default: return denied('unknown-content');
  }
}

export function isIndexable(target: IndexTarget): boolean {
  return getIndexDecision(target).indexable;
}

/**
 * Robots directive for a page's `metadata`. Blocked pages stay crawlable so link
 * equity still flows to the pages that did qualify.
 */
export function robotsFor(target: IndexTarget): { index: boolean; follow: boolean } {
  return { index: isIndexable(target), follow: true };
}

/** Every unit the sitemap may list, in manifest order. */
export function listIndexableUnits(): PageQuality[] {
  return Object.values(MANIFEST.units).filter((u) => evaluatePage(u).indexable);
}

/** Every lesson the sitemap may list. Empty while no lesson clears the prose floor. */
export function listIndexableLessons(): PageQuality[] {
  return Object.values(MANIFEST.lessons).filter((l) => evaluatePage(l).indexable);
}

export function manifestMeta(): { version: number; generatedAt: string; contentHash: string } {
  const { version, generatedAt, contentHash } = MANIFEST;
  return { version, generatedAt, contentHash };
}
